# fly.toml app configuration file generated for assistant-summer-sun-6786 on 2025-10-04T18:16:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'assistant-summer-sun-6786'
primary_region = 'iad'

[build]

[deploy]
  strategy = "immediate"

[http_service]
  internal_port = 5050
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = "5050"
  VOICE = "alloy"
  TEMPERATURE = "0.8"
  ASSISTANT_INSTRUCTIONS = "You are a helpful and friendly AI voice assistant. Be conversational and natural. Keep responses concise and to the point. Speak clearly and avoid overly long explanations unless asked."
  TODOIST_INSTRUCTIONS = "You have access to Todoist for task management. CRITICAL RULES: 1) ALWAYS confirm before creating, modifying, or deleting any task. State exactly what you will do and wait for explicit confirmation (yes/confirmed/go ahead). 2) If task details are ambiguous (spelling, project, due date), ask for clarification before proceeding. Only ask if genuinely uncertain. 3) After executing any action, report what was done clearly (e.g., 'I created a task called X with due date Y' or 'I marked task X as complete'). 4) For read-only operations (listing tasks, checking what's due), no confirmation needed. Never pretend to perform actions - always use the actual tools."
  TODOIST_MCP_URL = "https://mcp.zapier.com/api/mcp/mcp"

# Secrets (set via: fly secrets set KEY=value -a assistant-summer-sun-6786)
# - OPENAI_API_KEY
# - TWILIO_AUTH_TOKEN
# - TODOIST_MCP_PASSWORD
