# fly.toml app configuration file generated for assistant-summer-sun-6786 on 2025-10-04T18:16:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'assistant-summer-sun-6786'
primary_region = 'iad'

[build]

[deploy]
  strategy = "bluegreen"

[http_service]
  internal_port = 5050
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = "5050"
  VOICE = "alloy"
  TEMPERATURE = "0.8"
  SYSTEM_MESSAGE = "You are a helpful AI assistant. Be concise and direct in your responses. Keep answers brief unless asked for more detail."

# Secrets (set via: fly secrets set KEY=value)
# - OPENAI_API_KEY
# - TWILIO_AUTH_TOKEN
