name: Trunk Check

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  trunk-check:
    name: Trunk Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          # Use 'check-mode' to only report issues, or 'check' to block PRs
          check-mode: check
          # Post annotations on PRs
          post-annotations: true
          # Upload results to Trunk for tracking
          upload-series: true
